### ISSUE TITLE
Magento 2.4.7: CSP blocking of inline script in checkout

### ISSUE THREAD

**Issue by Webwijs** [webwinkelkeur/magento2#21]
The extension inserts an inline script in the body without a nonce-hash. So the content security policy blocks it in the checkout and breaks it.

This is the script in question:

```html
<script>
(function(url,id){var script=document.createElement('script');script.async=true;script.src=url+'/sidebar.js?id='+id+'&c='+cachebuster(10,id);var ref=document.getElementsByTagName('script')[0];ref.parentNode.insertBefore(script,ref);function cachebuster(refreshMinutes,id){var now=Date.now();var interval=refreshMinutes*60e3;var shift=(Math.sin(id)||0)*interval;return Math.floor((now+shift)/interval);}})("https:\/\/dashboard.webwinkelkeur.nl",****);
</script>
```

Solution: Add a nonce according to the Adobe developers manual.

https://developer.adobe.com/commerce/php/development/security/content-security-policies/#using-csp-nonce-provider-to-allow-inline-scripts

**Comment by TsankoBg** [comment]
Hi,

Thank you for reporting the issue. The issue will be addressed soon.

**Comment by TsankoBg** [comment]
Hi, thanks again for reporting this. The changes have been made:
* Added `nonce` to the inline script
* Added webwinkelkeur domain to `csp_whitelist.xml`
